services:
  db:
    container_name: authen-author-jwt
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=authen-author-jwt-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '8001:5432'

volumes:
  postgres-data:
